### ISSUE TITLE
where can I get private key ?

### ISSUE THREAD

**Issue by choiking** [rabbitx-io/rabbitx-python-client#7]
as title say.

**Comment by rabbitx-io** [comment]
You can get private key by exporting from metamask. We have enabled api key/secret signing as an option. You can create a new api key/secret by clicking the gear icon at the top.

![image](https://github.com/rabbitx-io/rabbitx-python-client/assets/114927084/d323b187-1238-43e9-9a3d-bcb96cca44c9)

![image](https://github.com/rabbitx-io/rabbitx-python-client/assets/114927084/a0c7ffe7-9426-4bfd-9050-80f167afecfc)
